### ISSUE TITLE
Roadmap for 1.0.0

### ISSUE THREAD

**Issue by krzksz** [krzksz/created#1]
I'm creating this issue to keep track of development progress across different repositories for created. Below is a TODO list of what should be done before we can call it stable and go with version 1.0.0 to be used in our projects.

## Core
- [ ] Move build-in commands outside from main package.
  - [ ] Init command.
  - [ ] Help command.
  - [ ] List command.
- [ ] Add documentation about:
  - [ ] How to use commands and plugins imported from npm.
  - [ ] How to use commands and plugins provided locally in the project.
  - [ ] How to apply and configure plugins and commands for certain project.
  - [ ] How to write your own commands and plugins both npm and local way.
- [ ] Add project badges and setup travisCI and greenkeeper.
## Commands
- [ ] Templates:
  - [ ] Copying and minifying HTML.
  - [ ] Compiling Twig templates using twig.js and/or atpl.js.
  - [ ] Compiling pug.js templates(?).
- [ ] Images:
  - [ ] Copying and minifying images.
  - [ ] Compiling SVG sprites.
- [ ] Scripts:
  - [ ] Copy + minfy.
  - [ ] Concat + minify.
  - [ ] Compile using webpack(should we provide different configuration for it etc. babel, typescript?).
  - [ ] Test using jest.
  - [ ] Lint using ESLint.
- [ ] Styles:
  - [ ] Compile using Sass + postCSS.
  - [ ] Lint using stylelint and/or sass-lint(?)
## Generators
- [ ] Command.
- [ ] Web application.
